import { UserResponse } from '../pocketbase-types';
import { ItemData } from './types/ItemData';

export const itemRows: ItemData[] = [
  {
    id: 'ABC2-23AS',
    location: '2F',
    name: 'Wooden Chair',
    quantity: 23,
    remarks: 'Sira yung paa sa likod',
    status: false,
    supplier: 'ValACE',
    type: 0,
    images: ['link 1', 'link 2'],
  },
  {
    id: 'DEF2-24AS',
    location: '3F',
    name: 'Wooden Table',
    quantity: 23,
    remarks: 'Sira yung paa sa harap',
    status: true,
    supplier: 'ValACE',
    type: 0,
    images: ['link 1', 'link 2'],
  },
  {
    id: 'GHI2-25AS',
    location: '3F',
    name: 'Wooden Pencil',
    quantity: 23,
    remarks: 'Sira yung paa sa harap',
    status: false,
    supplier: 'ValACE',
    type: 0,
    images: ['link 1', 'link 2'],
  },
  {
    id: 'JKL2-26AS',
    location: '3F',
    name: 'Wooden Eraser',
    quantity: 23,
    remarks: 'Sira yung pambura sa harap',
    status: true,
    supplier: 'ValACE',
    type: 0,
    images: ['link 1', 'link 2'],
  },
  {
    id: 'ABG2-23AS',
    location: '2F',
    name: 'Wooden Chair',
    quantity: 23,
    remarks: 'Sira yung paa sa likod',
    status: false,
    supplier: 'ValACE',
    type: 0,
    images: ['link 1', 'link 2'],
  },
  {
    id: 'DFF2-24AS',
    location: '3F',
    name: 'Wooden Table',
    quantity: 23,
    remarks: 'Sira yung paa sa harap',
    status: true,
    supplier: 'ValACE',
    type: 0,
    images: ['link 1', 'link 2'],
  },
  {
    id: 'GDI2-25AS',
    location: '3F',
    name: 'Wooden Pencil',
    quantity: 23,
    remarks: 'Sira yung paa sa harap',
    status: false,
    supplier: 'ValACE',
    type: 0,
    images: ['link 1', 'link 2'],
  },
  {
    id: 'JKS2-26AS',
    location: '3F',
    name: 'Wooden Eraser',
    quantity: 23,
    remarks: 'Sira yung pambura sa harap',
    status: true,
    supplier: 'ValACE',
    type: 0,
    images: ['link 1', 'link 2'],
  },
];
